App_DRF/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import routers
from app_DRF_start import views

router = routers.DefaultRouter()
router.register(r'test',views.InfoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('citup/',include('app_DRF_start.urls')),
    path('',include(router.urls)),
]

app_DRF_start/urls.py
from django.urls import path,include
from . import views
from . import push_fcm

app_name = 'app_DRF_start'

push_fcm.send_to_firebase_cloud_messaging()
# test_push.send_notification()
# Push.send_to_firebase_cloud_messaging()
urlpatterns = [
    # path('',include('rest_framework.urls',namespace='rest_framework_category')),
    path('main/',views.main, name = 'main'),
    path('login/',views.login,name='login'),
    path('about/',views.about,name='about'),
    path('data/',views.data,name = 'data'),
    path('mypage/',views.mypage,name='mypage'),
]

app_DRF_start/models.py
from django.db import models


# class AuthGroup(models.Model):
#     name = models.CharField(unique=True, max_length=150)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_group'
#
#
# class AuthGroupPermissions(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
#     permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_group_permissions'
#         unique_together = (('group', 'permission'),)
#
#
# class AuthPermission(models.Model):
#     name = models.CharField(max_length=255)
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
#     codename = models.CharField(max_length=100)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_permission'
#         unique_together = (('content_type', 'codename'),)
#
#
# class AuthUser(models.Model):
#     password = models.CharField(max_length=128)
#     last_login = models.DateTimeField(blank=True, null=True)
#     is_superuser = models.IntegerField()
#     username = models.CharField(unique=True, max_length=150)
#     first_name = models.CharField(max_length=150)
#     last_name = models.CharField(max_length=150)
#     email = models.CharField(max_length=254)
#     is_staff = models.IntegerField()
#     is_active = models.IntegerField()
#     date_joined = models.DateTimeField()
#
#     class Meta:
#         managed = False
#         db_table = 'auth_user'
#
#
# class AuthUserGroups(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_user_groups'
#         unique_together = (('user', 'group'),)
#
#
# class AuthUserUserPermissions(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'auth_user_user_permissions'
#         unique_together = (('user', 'permission'),)
#
#
# class DjangoAdminLog(models.Model):
#     action_time = models.DateTimeField()
#     object_id = models.TextField(blank=True, null=True)
#     object_repr = models.CharField(max_length=200)
#     action_flag = models.PositiveSmallIntegerField()
#     change_message = models.TextField()
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#
#     class Meta:
#         managed = False
#         db_table = 'django_admin_log'
#
#
# class DjangoContentType(models.Model):
#     app_label = models.CharField(max_length=100)
#     model = models.CharField(max_length=100)
#
#     class Meta:
#         managed = False
#         db_table = 'django_content_type'
#         unique_together = (('app_label', 'model'),)
#
#
# class DjangoMigrations(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     app = models.CharField(max_length=255)
#     name = models.CharField(max_length=255)
#     applied = models.DateTimeField()
#
#     class Meta:
#         managed = False
#         db_table = 'django_migrations'
#
#
# class DjangoSession(models.Model):
#     session_key = models.CharField(primary_key=True, max_length=40)
#     session_data = models.TextField()
#     expire_date = models.DateTimeField()
#
#     class Meta:
#         managed = False
#         db_table = 'django_session'

class Info(models.Model):
    id = models.IntegerField(db_column='id', primary_key=True)
    name = models.CharField(max_length=30)
    volume = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'info'
        app_label = 'app_DRF_start'

app_DRF_start/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator
from rest_framework import viewsets
from app_DRF_start.serializers import InfoSerializer
from app_DRF_start.models import Info
from rest_framework.decorators import api_view,permission_classes
from rest_framework.permissions import AllowAny
# from .push_fcm import send_to_firebase_cloud_messaging
from rest_framework.response import Response

# @api_view(['GET'])
# @permission_classes([AllowAny])
# def send_test_volume(request):
#     send_to_firebase_cloud_messaging.delay()
#     return Response({"message":"ok"})
def main(request):
    return render(request, 'app_DRF_start/CGV.html')

def login(request):
    return render(request,'app_DRF_start/CGV_login.html')

def about(request):
    return render(request,'app_DRF_start/CGV_About.html')

def data(request):
    page = request.GET.get('page', '1')
    infos = Info.objects.all()
    paginator = Paginator(infos, 20)
    page_obj = paginator.get_page(page)
    context = {'infos': page_obj}
    return render(request,'app_DRF_start/CGV_Data.html',context)

def mypage(request):
    return render(request,'app_DRF_start/CGV_mypage.html')

def sensor_view(request):
    page = request.GET.get('page', '1')
    infos = Info.objects.all()
    paginator = Paginator(infos, 20)
    page_obj = paginator.get_page(page)
    context = {'infos': page_obj}
    return render(request, 'app_DRF_start/sensorpage.html', context)


class InfoViewSet(viewsets.ModelViewSet):
    queryset = Info.objects.all()
    serializer_class = InfoSerializer

app_DRF_start/templates/app_DRF_start/CGV.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CGV</title>
 
    <!-- 외부 스타일시트 적용 -->
    {% load static %}
     <link rel ="stylesheet" type = "text/css" href="{% static 'app_DRF_start/CGV.css' %}">
</head>
<body>
    <header>
    	<img src="{% static 'img/logo.png'  %}" width="300" height="120">
        <div id="login" style="float:right; font-size: 25px;">
            <ul>
                <li><a href="{% url 'app_DRF_start:login' %}"><br>LOGIN </a></li>
                <li><a href="{% url 'app_DRF_start:mypage' %}">My Page</a></li>
            </ul> 
        </div>
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'app_DRF_start:main' %}">Home</a></li>
            <li><a href="{% url 'app_DRF_start:about' %}">About</a></li>
            <li><a href="{% url 'app_DRF_start:data'  %}">Data</a></li>
            <li><a href="https://www.data.go.kr/dataset/15015129/fileData.do">Portal</a></li>
        </ul>
        <hr>
    </nav>
    
    <aside id="top"> 
        <div class="user-wrap">       
            <div class="user-image">
                <center>
                <img src="{% static 'img/main.jpg' %}" srcset="{% static 'img/main.jpg' %} 300w,{% static 'img/main.jpg' %} 450w, {% static 'img/main.jpg' %} 600w" sizes="(min-width: 600px) 600px, (min-width: 450px) 450px, 300px" alt="responsive images">
                </center>
            </div>
            <div class="user-text">
                <p><br>Automatic Open & Compression<br>With<br>Saturation Sensor<br>Environment Data System<br></p>
            </div>
        </div>

    </aside>
    <section id="main">
    </section>    
</body>
</html>

app_DRF_start/templates/app_DRF_start/CGV_About.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CGV</title>
 
    <!-- 외부 스타일시트 적용 -->
    {% load static %}
    <link rel ="stylesheet" type = "text/css" href="{% static 'app_DRF_start/CGV.css' %}">

</head>
<body>
    <header>
        <img src="{% static 'img/logo.png' %}" width="300" height="110">
        <div id="login" style="float:right; font-size: 25px;">
            <ul>
                <li><a href="{% url 'app_DRF_start:login' %}"><br>LOGIN </a></li>
                <li><a href="{% url 'app_DRF_start:mypage' %}">My Page</a></li>
            </ul> 
        </div>
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'app_DRF_start:main' %}">Home</a></li>
            <li><a href="{% url 'app_DRF_start:about' %}">About</a></li>
            <li><a href="{% url 'app_DRF_start:data'  %}">Data</a></li>
            <li><a href="https://www.data.go.kr/dataset/15015129/fileData.do">Portal</a></li>
          </ul>
        <hr>
    </nav>
    
    <aside id="top"> 
        <div class="user-wrap">       
            <div>
        <img src="{% static 'img/about.png' %}" style="width: 700px; height: auto; float: left; margin-right: 50px;">
        <p style="font-size: 40px; font-weight : bold; font-family: arial;"><br>CGV</p>
        <p style="font-size: 20px;">"Clean Ground View"<br>원활하고 편리한 쓰레기통 관리를 통해 깨끗한 환경을 만들자는 의미를 담고 있으며, CIT_UP 프로젝트를 통해 쓰레기 관리의 중요성을 인지하고 환경에 대한 관심을 높여 다양한 연구에 도움이 되고자 하는 의미를 담았다.</p>

        <p style="font-size: 40px; font-weight: bold; font-family: arial;"><br>CIT_UP</p>
        <p style="font-size: 20px;">"Clean IT UP"<br> CIT_UP 프로젝트는 환경오염의 원인 중 한 가지인 쓰레기는 버리는 것 뿐만 아니라 관리 또한 중요하다는 점을 본 프로젝트를 통해 인식하기 위해 청소 관리자를 위한 시스템을 개발하려는 목적을 가지고 있다. 또한 청소 관리자를 위한 원활하고 편리한 쓰레기통 관리 시스템 제공과 발생된 쓰레기 별 빈도 데이터를 수집하여 다양한 연구에 사용하기 위한 프로젝트를 진행한다.<br>The CIT_UP project aims to develop a system for cleaning managers in order to recognize through this project that waste, one of the causes of environmental pollution, is important not only for processing but also for management. In addition, a project is carried out to provide a smooth and convenient trash can management system for cleaning managers and to collect data on frequency of generated garbage and use it for various studies.</p>

    </div>
        </div>
    </aside>
    <section id="main">
    </section>    
</body>
</html>

app_DRF_start/templates/app_DRF_start/CGV_Data.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CGV</title>
 
    <!-- 외부 스타일시트 적용 -->
    {% load static %}
     <link rel ="stylesheet" type = "text/css" href="{% static 'app_DRF_start/CGV.css' %}">
{#     <link rel ="stylesheet" type = "text/css" href="{% static 'app_DRF_start/pagestyle.css' %}">#}
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <script type="text/javascript" src="{% static 'app_DRF_start/saveAsExcel.js' %}"></script>
    <link rel="stylesheet" href="{% static 'app_DRF_start/bootstrap.min.css' %}">

</head>
<body style=" background-color: #EAF2E8;">
    <header>
    	<img src="{% static 'img/logo.png'  %}" width="300" height="120">
        <div id="login" style="float:right; font-size: 25px;">
            <ul>
                <li><a href="{% url 'app_DRF_start:login' %}"><br>LOGIN </a></li>
                <li><a href="{% url 'app_DRF_start:mypage' %}">My Page</a></li>
            </ul>
        </div>
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'app_DRF_start:main' %}">Home</a></li>
            <li><a href="{% url 'app_DRF_start:about' %}">About</a></li>
            <li><a href="{% url 'app_DRF_start:data'  %}">Data</a></li>
            <li><a href="https://www.data.go.kr/dataset/15015129/fileData.do">Portal</a></li>
        </ul>
        <hr>
    </nav>
    
    <section id="main">
        <div id = "contents">
        <p>쓰레기 수집 정보</p>

            <input type="button" value="Import as Excel" onclick="saveAsExcel('tableToExcel', 'sensor.xls')"/>
            <table id="tableToExcel">
                <thead>
                <tr>
                    <th style="width : auto;"><B>번</B></th>
                    <th style="width : auto;"><B>ID</B></th>
                    <th style ="width : auto;"><B>쓰레기 용량(%)</B></th>
                    <th style = "width: auto;"><B></B>날짜</th>
                </tr>
                </thead>
                <tbody>
                    {% for info in infos %}
                    <tr>
                        <td>{{info.id}}</td>
                        <td>{{info.name}}</td>
                        <td>{{info.volume}}%</td>
                        <td>{{info.date}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
<!--             페이징처리 시작-->
            <div class ="pagination" style="margin : 0px;">
                <ul class="pagination justify-content-center" style="margin-left : 15px;" >            <!-- 이전페이지 -->

                    <!-- 이전페이지 -->
                    {% if infos.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?&page={{ infos.previous_page_number }}">이전</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                    </li>
                    {% endif %}
                    <!-- 페이지리스트 -->
                    {% for page_number in infos.paginator.page_range %}
                    {%  if page_number >= infos.number|add:-4 and page_number <= infos.number|add:4  %}
                    {% if page_number == infos.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    <!-- 다음페이지 -->
                    {% if infos.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?&page={{ infos.next_page_number }}">다음</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                    </li>
                    {% endif %}
                </ul>


            </div>
            <!-- 페이징처리 끝 -->
        </div>
    </section>    
</body>
</html>

app_DRF_start/templates/app_DRF_start/CGV_login.html
<!DOCTYPE html>
<html>
    <head>
        <title>LOGIN</title>
        <meta charset="utf-8">
        {%  load static %}
        <link rel ="stylesheet" type = "text/css" href="{% static 'app_DRF_start/CGV_login.css' %}">
        <link href="https://fonts.googleapis.com/earlyaccess/notosanskr.css" rel="stylesheet">
        <style>
            h1{text-align: center;}
        </style>
    </head>

    <body>
        <br><h1>LOGIN</h1>
        <div class="login-form">
            <form>            
                <input id="LOGIN_ID" class="text-field" type="text" name="id"  placeholder="아이디 혹은 사용자 이름">
                <input id="LOGIN_PW" class="text-field" type="text" name="password"  placeholder="비밀번호">
                <button id="LOGIN_BTN" class="login-btn" type="button" disabled>로그인</button>
            </form>

            <div class="login_bottom">
                <a href="#">비밀번호를 잊어버리셨나요?</a>
            </div>
        </div>
        <script src="{% static 'app_DRF_start/CGV_login.js' %}" defer=""></script>
    </body>
</html>

app_DRF_start/templates/app_DRF_start/CGV_mypage.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Page</title>
        <meta charset="utf-8">
        {% load static %}
        <link rel="stylesheet" href="{% static 'app_DRF_start/CGV_mypage.css' %}">
        <link href="https://fonts.googleapis.com/earlyaccess/notosanskr.css" rel="stylesheet">
        <style>
            h1{text-align: center;}
        </style>
    </head>

    <body>
        <br><h1>My Page</h1>
        <div class="login-form">
            <form>            
                <input id="LOGIN_ID" class="text-field" type="text" name="id"  placeholder="아이디 혹은 사용자 이름">
                <input id="LOGIN_PW" class="text-field" type="text" name="password"  placeholder="비밀번호">
                <button id="LOGIN_BTN" class="login-btn" type="button" disabled>로그인</button>
            </form>
        </div>
        <script src="{% static 'app_DRF_start/CGV_login.js' %}" defer=""></script>
    </body>
</html>

app_DRF_start/templates/app_DRF_start/sensorpage.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>CIT_UP</title>
    {% load static %}
    <link rel ="stylesheet" type = "text/css" href="{% static 'app_DRF_start/pagestyle.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <script type=src="{% static 'app_DRF_start/saveAsExcel.js' %}" defer=""></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <meta name = "viewport" content="width=device-width, initial-scale=1">


</head>
<body>
<header>
    <div id = "text">
     <a style="color :  #009127;">CIT_UP</a>
    </div>
</header>




    <div id = "main">
        <div id = "sidebar">카테고리 기능 추가중 입니다.</div>
        <div id = "contents">
            <p>쓰레기 수집 정보</p>

            <input type="button" value="Import as Excel" onclick="saveAsExcel('tableToExcel', 'sensor.xls')"/>
            <table id="tableToExcel">
                <thead>
                <tr>
                    <th style="width : auto;"><B>번</B></th>
                    <th style="width : auto;"><B>ID</B></th>
                    <th style ="width : auto;"><B>쓰레기 용량(%)</B></th>
                    <th style = "width: auto;"><B></B>날짜</th>
                </tr>
                </thead>
                <tbody>
                    {% for info in infos %}
                    <tr>
                        <td>{{info.id}}</td>
                        <td>{{info.name}}</td>
                        <td>{{info.volume}}%</td>
                        <td>{{info.date}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
<!--             페이징처리 시작-->
            <div class ="pagination" style="margin : 0px;">
                <ul class="pagination justify-content-center" style="margin-left : 15px;" >            <!-- 이전페이지 -->

                    <!-- 이전페이지 -->
                    {% if infos.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?&page={{ infos.previous_page_number }}">이전</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                    </li>
                    {% endif %}
                    <!-- 페이지리스트 -->
                    {% for page_number in infos.paginator.page_range %}
                    {%  if page_number >= infos.number|add:-4 and page_number <= infos.number|add:4  %}
                    {% if page_number == infos.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?&page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    <!-- 다음페이지 -->
                    {% if infos.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?&page={{ infos.next_page_number }}">다음</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                    </li>
                    {% endif %}
                </ul>


            </div>
            <!-- 페이징처리 끝 -->
        </div>

    </div>
    <div id = "footer">푸터 영역이다</div>

</body>
</html>